### ISSUE TITLE
Clarification of terminology and scope

### ISSUE THREAD

**Issue by lrosenthol** [w3c/tdm-reservation-protocol#1]
The README document refers to both `Web content` and `content accessible on the Web`, but it is not clear to me if (a) they are the same thing, in this context and (b) what exactly is meant.   There are also references in the README to various asset formats - images, videos, text, etc.  Does this CG plan to address all of these types of assets?  And if so, in what publishing or distribution contexts?

**Comment by llemeurfr** [comment]
Thanks for the remark Leonard. I

The EU DSM Directive introduces an exception "for reproductions and extractions of lawfully accessible works and other subject matter for the purposes of text and data mining." Because we are working here in the scope of the Web, we'll focus on content accessible through the Web, which is the core problem organizations want to solve. 

Re. the different types of assets, the CG will first establish and validate requirements; these have already been discussed in a pre-CG group and there is a will to enable expressing "TDM rights" for any kind of Web resource (included in / reference from an HTML page or not). The technical solution which will be chosen may limit flexibility here, there is a balance to find between simplicity and features.  

Re. the publishing / distribution context, the other thing the CG will establish first is a set of use-cases which will clarify this (here also a preliminary work has been done already).

**Comment by lrosenthol** [comment]
@llemeurfr In the Requirements document (https://github.com/w3c/tdm-reservation-protocol/blob/main/docs/requirements.md) it states:
>Specify how a rightsholder can declare TDM rights on each individual Web resource he controls, when such Web resources are present in a Web page.

I think this needs to change to use the language that you have above - "included in / reference from" - instead of "present" (as I find present as too vague)

**Comment by lrosenthol** [comment]
> The technical solution which will be chosen may limit flexibility here, there is a balance to find between simplicity and features.

I think you are putting the cart before the horse here.  We haven't even finalized a charter or a set of requirements - and you are already deciding that we are not going to address them all?!?!

**Comment by llemeurfr** [comment]
In the initial discussions which ended up with these draft requirements, there was a split between primary requirements = "must have" and secondary requirements = "good to have" (if this is not detrimental to the simplicity of the solution).
 
This is how we can IMHO fulfill the high level requirement 3 = Be easy to implement, with no economic or technical barriers (= KISS principle).

**Comment by lrosenthol** [comment]
I agree that the solution shall be "Be easy to implement, with no economic or technical barriers"

Within that definition, there is a myriad of possibilities....
