### ISSUE TITLE
A general consideration on the way towards our discussion is aimed

### ISSUE THREAD

**Issue by claudiotubertini** [w3c/tdm-reservation-protocol#17]
I understand that simplicity is a basic requirement, but what worries me is TDM exception might become something similar to GDPR cookie declaration: GDPR means more than you have to click on the "ok" button of a popup and forget, it is not a simple nuisance designed by Brussel bureaucrats, as is interpreted by all website publishers. As regards TDM, if a publisher wants to opt out, it should be gently pushed towards offering a licence not just to send an http header with TDMa=1.
If you were a publisher which route would you follow?

| Command | Cost | &Delta; Earnings |
| --- | --- | --- |
| `TDMa=0` | -1 | 0 | 
| `TDMa=1` | -1 | 0 | 
| `TDMa=2` | -2 | > 0 | 

&Delta; Earnings are respect to present situation without machine reading proposal. There is always a cost in implementing the proposal.
No one will never follow the route TDMa=0. Among those publishers that decide to do something to avoid the exception everybody will choose TDMa=1 if there is no gain in TDMa=2.

**Comment by llemeurfr** [comment]
When you're listing Earnings, are you speaking about rightsholder or TDM actor earnings? 

Because for rightsholders I would rather say:

| Command | &Delta; Earnings | Reason |
| --- | --- | --- | 
| `TDMa=0` | > 0 |  by stating that its content is open to data mining worldwide, the rightsholder avoids spending time responding to TDM actors outside EU |
| `TDMa=1` | > 0 |  by stating that he is opting-out from the EU TDM exception, the rightsholder applies the freedom expressed in the Article 4 of the DSM |
| `TDMa=2` | > 0 | by stating that he is opting-out from the EU TDM exception but that a license can be acquired, the rightsholder is in position to get some money from commercial TDM actors |

Respectively, for TDM Actors :
 
| Command | &Delta; Earnings | Reason |
| --- | --- | --- | 
| `TDMa=0` | > 0 |  A TDM Actor knows that he can mine the content, without having to spend time contacting the rightsholder |
| `TDMa=1` | > 0 |   A TDM Actor knows that he must refrain to mine the content if he's not a European Reserch org; no time lost |
| `TDMa=2` | > 0 | A TDM Actor gets a direct contact with the rightsholder; no time lost |

**Comment by llemeurfr** [comment]
Besides that I agree that the spec can gently push rightsholders to add a policy to their TDM choice, i.e. it is up to us to promote TDMa=2 rather than TDMa=1.  For that, the policy must be simple enough to manage.

**Comment by claudiotubertini** [comment]
The reason behind my comment is that I would like to stress the importance of licensing. In the last speach I heard during the TDM meeting someone spoke about separating the opting out from the possibility to offer a license. I think that would be a big mistake.

**Comment by giuliamarangoni** [comment]
Dear Claudio and all, 
happy to further discuss this at our meeting today. However, let me anticipate one thought. I think that it is fundamental that all the technical solutions envisaged will be neutral with respect to rightsholders business models and decisions. We are doing our best to provide technology solutions that are as easy as possible to adopt by all rightolders (and miners),  to enable effective communication of TMD rights and licensing information; however, technical solutions are intended to serve users, without setting any constraints or their decisions.

**Comment by claudiotubertini** [comment]
I agree, of course. Technical solutions should be technical and usually do
not imply any moral obligations.  But the solution we try to define has the
purpose to clarify to readers (that is the miners) in which sense and
which are the details that put a restriction on the freedom allowed by the
law. If we devise such a simple automatic procedure that makes everybody
opt-out to the exception we obtain the same result as GDPR, a simple
annoyance before accessing a web site.
What we can do is simply require that tdm-b is always present.

*Instead of:*

TDM-b *SHOULD* be set only if the value of TDM-a is 2.

The absence of TDM-b if the value of TDM-a is 2 is considered a protocol
error. In such a case TDM Agents *MUST* consider that the value of TDM-a is
1.

*We can have:*

TDM-b *SHOULD* be alway set.

The absence of TDM-b  is considered a protocol error. In such a case TDM
Agents *MUST* consider that the value of TDM-a is 0.
See you in less than an hour.
Claudio
